/*
THIS IS THE POPUP SCRIPT
WHEN INVOKED, IT CALCULATES GPA WITH ALL MOST RECENT STORED GRADES.
INCLUDES A BUTTON TO OPEN, UPDATE, THEN CLOSE ALL SAVED CLASSES AS
A PAINLESS QUICK WAY TO UPDATE GPA.
 */


let classes = ;
let GPA;
let gpaFloats;
let numClasses;

